### ISSUE TITLE
Multigrabs: Group action and enemy HP

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#53]
### Summary
 When toppling an enemy and then having a third jump in plays the group animation, but doesn't drain Joe's health.  Depending if it was a KO or a swoon, the toppled enemy will either be fully KO'd at the end (in the first scenario), or partially KO'd and can be sex'd again (in the second one).  The second enemy in this case gets off scot free (save for their health bar being where they'd end up after the animation; i.e., Daku's leap).  If swooned, their health bar remains (but slowly drains during the animation)

### Consequences
Might be a bit confusing gameplay-wise.

### Steps to recreate
1. Top the enemy in any way near another compatible enemy
2. Hope that the third jump in

### Examples
T0053 at Dropbox

### Error Log
Was not provided

### Configuration and system information
Was not provided

**Comment by FullFrontalFrog** [comment]
Thanks for the video! It actually features a couple other visual bugs, but I'm gonna focus on the HP bug first.

Seems like this bug happens because Joe initiates charm sex with Daku A first, then Daku B jumps on. Daku A takes the damage instead of Joe. I think my code has Daku A as the "bottom" in the stack of characters, but that should be Joe.

**Comment by FullFrontalFrog** [comment]
A possible fix has been made for v0.18.400.

**Comment by MagLjudik** [comment]
Fixed in 0.18.500
