### ISSUE TITLE
Game won't start on Windows

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#58]
### Summary
From one of the patrons:
> Good evening, after downloading the new version the game won't load anymore. Tried loading a save and a new game but it seems to be stuck on the level loading part. Downloaded the previous version and that also doesn't work anymore. Did check the logs and saw about a thousand time the error NullReferenceException: Object reference not set to an instance of an object.

I could not replicate this error. Supposedly, it's because of invalid symbols in the patron's path to game.

### Consequences
Game cannot be started

### Error Log
[Player-prev (2).log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/10327199/Player-prev.2.log)
[Player (2).log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/10327200/Player.2.log)

### Configuration and system information
Was not provided

**Comment by MagLjudik** [comment]
Issue was resolved when patron moved the game to a valid path. 

I'll add path issue to FAQ for future similar cases.

**Comment by FullFrontalFrog** [comment]
Thanks for keeping this here as reference, Mag!

Issue stems from the use of a folder that has a single space as its name:
`D:/Games/ /Oh So Hero!/OhSoHero_Data/data.unity3d`

Since I'm using built-in methods from Unity/Microsoft to get the game's directory path, it's unlikely I can write a solution that will allow this.

Windows is built on top of a lot of old tech, so to keep things working smoothly, try to use normal folder names.
